//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public int facturaDetalleId { get; set; }
        public int facturaId { get; set; }
        public int productoId { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
        public decimal subTotal { get; set; }
        public decimal isv { get; set; }
        public bool estado { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
