//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kardex
    {
        public System.DateTime Fecha { get; set; }
        public string Categoria { get; set; }
        public string descripcion { get; set; }
        public int Compra { get; set; }
        public int Venta { get; set; }
        public Nullable<int> Acumulado { get; set; }
    }
}
