//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompraDetalle
    {
        public int ordenCompraDetalleId { get; set; }
        public int compraId { get; set; }
        public int productoId { get; set; }
        public int cantidad { get; set; }
        public decimal costo { get; set; }
        public decimal isv { get; set; }
        public int estadoId { get; set; }
        public bool estado { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual OrdenCompra OrdenCompra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
